[app]
name = "Petal Hero"
menu = "Games"
wifi_preference = false

[entry]
class = "PetalHero"

[metadata]
author = "dos"
license = "GPL-3.0-or-later"
url = "https://git.flow3r.garden/dos/PetalHero"
description = "Rhythm game compatible with Frets on Fire"
version = 0
