[app]
name = "Petal Hero"
category = "Games"
menu = "Apps" # fallback for firmwares older than 1.3.0
wifi_preference = false

[entry]
class = "PetalHero"

[metadata]
author = "dos"
license = "GPL-3.0-or-later"
url = "https://git.flow3r.garden/dos/PetalHero"
description = "Rhythm game compatible with Frets on Fire"
version = 1
